exam_question/urls.py
from django.urls import path

from exam_question import views, list_views

app_name = 'exam_question'

urlpatterns = [
    path('exam_register/', list_views.examiner_exam_reg, name='exam_register'),
    path('choose_exam/', views.choose_exam, name='choose_exam'),
    path('check_question/', views.check_question, name='check_question'),
    path('my_details/', list_views.examiner_details, name='my_details'),
    path('my_questions/', list_views.list_questions, name='my_questions'),
    path('edit/<str:question_id>/', views.edit_question, name='edit'),


    # financial accounting questions
    path('account_ss1/', views.accounts_ss1, name='account_1'),
    path('account_ss2/', views.accounts_ss2, name='account_2'),
    path('account_ss3/', views.accounts_ss3, name='account_3'),

    # agric questions
    path('agric_ss1/', views.agric_ss1, name='agric_1'),
    path('agric_ss2/', views.agric_ss2, name='agric_2'),
    path('agric_ss3/', views.agric_ss3, name='agric_3'),

    # biology questions
    path('biology_ss1/', views.biology_ss1, name='biology_1'),
    path('biology_ss2/', views.biology_ss2, name='biology_2'),
    path('biology_ss3/', views.biology_ss3, name='biology_3'),

    # chemistry questions
    path('chemistry_ss1/', views.chemistry_ss1, name='chemistry_1'),
    path('chemistry_ss2/', views.chemistry_ss2, name='chemistry_2'),
    path('chemistry_ss3/', views.chemistry_ss3, name='chemistry_3'),

    # civic questions
    path('civic_ss1/', views.civic_ss1, name='civic_1'),
    path('civic_ss2/', views.civic_ss2, name='civic_2'),
    path('civic_ss3/', views.civic_ss3, name='civic_3'),

    # commerce questions
    path('commerce_ss1/', views.commerce_ss1, name='commerce_1'),
    path('commerce_ss2/', views.commerce_ss2, name='commerce_2'),
    path('commerce_ss3/', views.commerce_ss3, name='commerce_3'),

    # crs questions
    path('crs_ss1/', views.crs_ss1, name='crs_1'),
    path('crs_ss2/', views.crs_ss2, name='crs_2'),
    path('crs_ss3/', views.crs_ss3, name='crs_3'),

    # economics questions
    path('economics_ss1/', views.economics_ss1, name='economics_1'),
    path('economics_ss2/', views.economics_ss2, name='economics_2'),
    path('economics_ss3/', views.economics_ss3, name='economics_3'),

    # english literature questions
    path('eng_literature_ss1/', views.eng_literature_ss1, name='eng_lit_1'),
    path('eng_literature_ss2/', views.eng_literature_ss2, name='eng_lit_2'),
    path('eng_literature_ss3/', views.eng_literature_ss3, name='eng_lit_3'),

    # english questions
    path('english_ss1/', views.english_ss1, name='english_1'),
    path('english_ss2/', views.english_ss2, name='english_2'),
    path('english_ss3/', views.english_ss3, name='english_3'),

    # further mathematics questions
    path('further_maths_ss1/', views.further_maths_ss1, name='further_maths_1'),
    path('further_maths_ss2/', views.further_maths_ss2, name='further_maths_2'),
    path('further_maths_ss3/', views.further_maths_ss3, name='further_maths_3'),

    # geography questions
    path('geography_ss1/', views.geography_ss1, name='geography_1'),
    path('geography_ss2/', views.geography_ss2, name='geography_2'),
    path('geography_ss3/', views.geography_ss3, name='geography_3'),

    # government questions
    path('government_ss1/', views.government_ss1, name='government_1'),
    path('government_ss2/', views.government_ss2, name='government_2'),
    path('government_ss3/', views.government_ss3, name='government_3'),

    # marketing questions
    path('marketing_ss1/', views.marketing_ss1, name='marketing_1'),
    path('marketing_ss2/', views.marketing_ss2, name='marketing_2'),
    path('marketing_ss3/', views.marketing_ss3, name='marketing_3'),

    # mathematics questions
    path('maths_ss1/', views.maths_ss1, name='maths_1'),
    path('maths_ss2/', views.maths_ss2, name='maths_2'),
    path('maths_ss3/', views.maths_ss3, name='maths_3'),

    # physics questions
    path('physics_ss1/', views.physics_ss1, name='physics_1'),
    path('physics_ss2/', views.physics_ss2, name='physics_2'),
    path('physics_ss3/', views.physics_ss3, name='physics_3'),

    # yoruba questions
    path('yoruba_ss1/', views.yoruba_ss1, name='yoruba_1'),
    path('yoruba_ss2/', views.yoruba_ss2, name='yoruba_2'),
    path('yoruba_ss3/', views.yoruba_ss3, name='yoruba_3'),

]

exams/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from . import views
from django.conf import settings

app_name = 'exams'

urlpatterns = [
    path('add_department/', views.add_department, name='add_department'),
    path('add_department_save/', views.add_department_save, name='add_department_save'),
    path('edit_department/', views.edit_department, name='edit_department'),
    path('edit_department_save/', views.edit_department_save, name='edit_department_save'),
    path('add_subject/', views.add_subject, name='add_subject'),
    path('add_subject_save/', views.add_subject_save, name='add_subject_save'),
    path('add_student_class/', views.add_student_class, name='add_student_class'),
    path('add_student_class_save/', views.add_student_class_save, name='add_student_class_save'),
    path('add_student_level/', views.add_student_level, name='add_student_level'),
    path('add_student_level_save/', views.add_student_level_save, name='add_student_level_save'),

    path('ajax_question/', views.set_ajax_question, name='ajax_question'),
    path('create_question/', views.CreateQuestion.as_view(), name='create_question'),
    path('update_question/', views.UpdateQuestion.as_view(), name='update_question'),

    path('radio_question/', views.answer, name='radio_question'),

    path('register/', views.register_exam, name='register_exam'),
    path('question/', views.exam_question, name='question'),
    path('answer/', views.student_answer, name='answer'),

]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

'''
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''

school_online/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls', namespace='landing')),
    path('users/', include('users.urls', namespace='users')),
    path('exams/', include('exams.urls', namespace='exams')),
    path('question/', include('set_question.urls', namespace='question')),
    path('exam_question/', include('exam_question.urls', namespace='exam_question')),
    path('student/', include('students.urls', namespace='student'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path

from students import views

app_name = 'student'
urlpatterns = [
    path('select_subject/', views.select_subject, name='select_subject'),
    path('get_question/', views.get_question, name='get_question'),
    path('question/', views.question, name='question')
]

users/urls.py
from django.urls import path
# from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccess, name='signup_success'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('candidate_profile/', views.candidate_edit_profile, name='candidate_profile'),
    path('examiner_profile/', views.examiner_edit_profile, name='examiner_profile'),
    path('candidate_detail/', views.candidate_profile, name='candidate_detail'),
    path('examiner_detail/', views.examiner_profile, name='examiner_detail'),
    path('update_candidate/', views.update_candidate, name='update_candidate'),
    path('update_examiner/', views.update_examiner, name='update_examiner'),

]

users/models.py
import random
import string

from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
# Create your models here.
# from phonenumber_field.modelfields import PhoneNumberField
from django.db.models.signals import post_save
from django.dispatch import receiver

def random_code(digit=7, letter=3):
    sample_str = ''.join((random.choice(string.digits) for i in range(digit)))
    sample_str += ''.join((random.choice(string.ascii_uppercase) for i in range(letter)))

    sample_list = list(sample_str)
    final_string = ''.join(sample_list)
    return final_string


'''
def id_gen(size=10, chars=string.ascii_uppercase + string.digits):
	return ''.join(random.choice(chars) for _ in range(size))
'''


class CustomUser(AbstractUser):
    unique_id = models.CharField(default=random_code, max_length=10)
    STATUS = [
        ('candidate', 'candidate'),
        ('examiner', 'examiner')
    ]
    status = models.CharField(choices=STATUS, max_length=20, default=False)


User = get_user_model()

class SchoolAdmin(models.Model):
    admin = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.last_name} {self.user.first_name} ({self.user.unique_id})'


class Candidate(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.last_name} {self.user.first_name} ({self.user.unique_id})'


class CandidateProfile(models.Model):
    candidate = models.OneToOneField(User, on_delete=models.CASCADE)
    middle_name = models.CharField(max_length=25, help_text='Enter your middle name here if any', null=True)
    # STATUS = [('candidate', 'candidate'),]
    # status = models.CharField(choices=STATUS, max_length=10, default='candidate')
    GENDER = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]
    gender = models.CharField(choices=GENDER, max_length=10, null=True)
    date_of_birth = models.DateField(help_text='Format: YYYY-MM-DD', null=True)
    age = models.BigIntegerField(null=True)
    address = models.CharField(max_length=300, null=True)
    RELIGION = [
        ('Christian', 'Christianity'),
        ('Muslim', 'Islam'),
    ]
    religion = models.CharField(choices=RELIGION, max_length=20, null=True)
    phone_number = models.CharField(max_length=20, null=True)
    # phone_number = PhoneNumberField(null=False, blank=False, unique=True)
    height = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    hobbies = models.CharField(max_length=200, null=True)
    profile_picture = models.ImageField(upload_to='profile_pics/%Y/%m/%d/', null=True)
    about_me = models.TextField(max_length=300, help_text='Write something about yourself, not more than 300 words', null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.candidate.last_name} {self.candidate.first_name} ({self.candidate.unique_id})'


class Examiner(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.last_name} {self.user.first_name} ({self.user.unique_id})'


class ExaminerProfile(models.Model):
    examiner = models.OneToOneField(User, on_delete=models.CASCADE)
    TITLE = [
        ('Mr', 'Mister'),
        ('Mrs', 'Mistress'),
        ('Dr', 'Doctor'),
        ('Prof', 'Professor'),
        ('Engr', 'Engineer'),
        ('Chief', 'Chief'),
    ]
    title = models.CharField(choices=TITLE, max_length=10, null=True)
    middle_name = models.CharField(max_length=25, help_text='Enter your middle name here if any', null=True)
    # STATUS = [('examiner', 'examiner'),]
    # status = models.CharField(choices=STATUS, max_length=10, default='candidate')

    QUALIFICATION = [
        ('NCE', 'NCE'),
        ('HND', 'HND'),
        ('B.Sc', 'B.Sc'),
        ('M.Sc', 'M.Sc'),
        ('PhD', 'PhD'),
    ]
    qualification = models.CharField(choices=QUALIFICATION, max_length=8, null=True)
    document = models.FileField(upload_to='documents/%Y/%m/%d/', null=True)
    profile_picture = models.ImageField(upload_to='profile_pics/%Y/%m/%d/', null=True)
    discipline = models.CharField(max_length=200, null=True)
    published_work = models.URLField(max_length=200, null=True)
    GENDER = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]
    gender = models.CharField(choices=GENDER, max_length=10, null=True)
    date_of_birth = models.DateField(help_text='Format: YYYY-MM-DD', null=True)
    age = models.IntegerField(null=True)
    address = models.CharField(max_length=300, null=True)
    RELIGION = [
        ('Christian', 'Christianity'),
        ('Muslim', 'Islam'),
    ]
    religion = models.CharField(choices=RELIGION, max_length=20, null=True)
    phone_number = models.CharField(max_length=20, null=True)
    # phone_number = PhoneNumberField(null=False, blank=False, unique=True)
    height = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    about_me = models.TextField(max_length=300, help_text='Write something about yourself, not more than 300 words' ,null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.title} {self.examiner.first_name} {self.examiner.last_name} ({self.examiner.unique_id})'

@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.is_staff == True:
            SchoolAdmin.objects.create(admin=instance)
        if instance.status == 'candidate':
            Candidate.objects.create(user=instance)
            CandidateProfile.objects.create(candidate=instance)
        if instance.status == 'examiner':
            Examiner.objects.create(user=instance)
            ExaminerProfile.objects.create(examiner=instance)

@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.status == 'admin':
        instance.schooladmin.save()
    if instance.status == 'candidate':
        instance.candidate.save()
        instance.candidateprofile.save()
    if instance.status == 'examiner':
        instance.examiner.save()
        instance.examinerprofile.save()

# model for candidates to register for exams
# create another app for examiners to set questions and students to register for and write exams

users/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from . models import CustomUser, CandidateProfile, ExaminerProfile
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


# forms for custom user login
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('status', 'username', 'email', 'first_name', 'last_name')     # UserCreationForm.Meta.fields + ('unique_id',)

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('status', 'username', 'email', 'first_name', 'last_name')  # UserCreationForm.Meta.fields

# form for user login:
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

# form for candidates to update profile

class UserModelForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('status', )

class CandidateProfileForm(forms.ModelForm):
    class Meta:
        model = CandidateProfile
        exclude = ['candidate', 'profile_date', 'candidate_id']

    helper = FormHelper()
    helper.form_class = 'form-group'
    helper.layout = Layout(
        Field('middle_name', css_class='form-control'),
        Field('gender', css_class='form-control'),
        Field('date_of_birth', css_class='form-control'),
        Field('age', css_class='form-control'),
        Field('address', css_class='form-control'),
        Field('religion', css_class='form-control'),
        Field('phone_num', css_class='form-control'),
        Field('height', css_class='form-control'),
        Field('hobbies', css_class='form-control'),
        Field('about_me', css_class='form-control'),

    )

# view for examiners to update profile
class ExaminerProfileForm(forms.ModelForm):
    class Meta:
        model = ExaminerProfile
        exclude = ['examiner', 'profile_date']

users/templates/users/about.html
{% extends 'landing/base1.html' %}

<section id="about-section" class="about-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title text-center wow fadeInDown" data-wow-duration="2s" data-wow-delay="50ms">
                    <h2>About Us</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-5">
                <div class="about-img">
                    <img src="{% static 'asset/images/corporate1.jpg' %}" class="img-responsive" alt="About images">
                    <div class="head-text">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec iaculis metus vitae ligula elementum ut luctus lorem facilisis.</p>
                        <span>CEO, Themebean</span>
                    </div>
                </div>
            </div>
            <div class="col-md-7">
                <div class="about-text">
                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi.</p>
                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                </div>

                <div class="about-list">
                    <h4>Some important Feature</h4>
                    <ul>
                        <li><i class="fa fa-check-square"></i>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.</li>
                        <li><i class="fa fa-check-square"></i>Lorem ipsum dolor sit amet, consectetur adipiscing adipiscing.</li>
                        <li><i class="fa fa-check-square"></i>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusan.</li>
                        <li><i class="fa fa-check-square"></i>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                        <li><i class="fa fa-check-square"></i>Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</li>
                        <li><i class="fa fa-check-square"></i>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                    </ul>

                    <h4>More Feature</h4>
                    <ul>
                        <li><i class="fa fa-check-square"></i>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.</li>
                        <li><i class="fa fa-check-square"></i>Lorem ipsum dolor sit amet, consectetur adipiscing adipiscing.</li>
                        <li><i class="fa fa-check-square"></i>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusan.</li>
                        <li><i class="fa fa-check-square"></i>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                    </ul>
                </div>

            </div>



        </div>
    </div>
</section>

users/templates/users/candidate.html
{% extends 'landing/base1.html' %}

{% block title %}Candidate Details{% endblock %}

{% block content %}
    Profile Picture: {{ profile_pic }}<br>
    Status: {{ status }}<br>
    Unique ID: {{ unique_id }}<br>
    Middle Name: {{ middle_name }}<br>
    Username: {{ username }}<br>
    Gender: {{ gender }}<br>
    Date of Birth: {{ dob }}<br>
    Age: {{ age }}<br>
    Religion: {{ religion }}<br>
    Phone Number: {{ phone_num }}<br>
    Email: {{ email }}<br>
    height: {{ height }}<br>
    Hobbies: {{ hobbies }}<br>
    About You: {{ about_me }}

    <h2>Click <a href="{% url 'users:update_candidate' %}">HERE</a> to update your profile</h2>
    <p>Register for examination <a href="{% url 'exams:register_exam' %}">HERE</a></p>
    <p>Take Exams <a href="{% url 'student:select_subject' %}">HERE</a></p>
{% endblock content %}

users/templates/users/candidate_profile.html
{% extends 'landing/base1.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Candidate Profile Form{% endblock %}

{% block content %}
    <div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <strong>Username: {{ user }}</strong><br>
        <strong>Status: {{ status }}</strong><br><br>
        {{ profile_form|crispy }}
        {{ form.media }}
        <p><input type="submit" value="Update"></p>
    </form>
{% endblock content %}

users/templates/users/candidate_profile_detail.html
{% extends 'landing/base1.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Candidate Profile Details{% endblock %}

{% block content %}
    <div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <div>
        <h2>Welcome, {{ last_name }} {{ first_name }},</h2>
        <h2>Here are your personal profile details:</h2>
        <div>
            <p>
                <strong>
                    User: {{ user }}<br>
                    User id: {{ unique_id }}<br>
                    Username: {{ username }}<br>
                    Status: {{ status }}<br>
                    Middle Name: {{ middle_name }}<br>
                    Gender: {{ gender }}<br>
                    Age: {{ age }}<br>
                    Address: {{ address }}<br>
                    Religion: {{ religion }}<br>
                    Phone Number: {{ phone }}<br>
                    Email: {{ email }}<br>
                    Height: {{ height }}<br>
                    Hobbies: {{ hobbies }}<br>
                    About You: {{ about_me }}<br>
                </strong>
            </p>
        </div>
        <p>Register for examination <a href="{% url 'exams:register_exam' %}">HERE</a></p>
        <p>Take Exams <a href="{% url 'exams:answer' %}">HERE</a></p>
    </div>
{% endblock content %}

users/templates/users/edit_profile.html
{% extends 'landing/base1.html' %}
{% load static %}

{% block title %}Update Profile{% endblock %}

{% block content %}
    <div>
        {% if request.user.is_authenticated %}
            {% if request.user.status == 'candidate' %}
                <p>To update your profile, click <a href="{% url 'users:candidate_profile' %}">Update Candidate Profile</a></p>
                <p>To register for examination, click</p>
                <p>To take examination, click</p>
            {% elif request.user.status == 'examiner' %}
                <a href="{% url 'users:examiner_profile' %}">Update Examiner Profile</a>
            {% else %}
                <h2>Please register as either a candidate or an examiner</h2>
            {% endif %}

        {% endif %}

    </div>
{% endblock content %}

users/templates/users/examiner.html
{% extends 'landing/base1.html' %}
{% load static %}

{% block title %}Examiner Profile Detail{% endblock %}

{% block content %}
    Profile Picture: {{ profile_pic }}<br>
    Unique ID: {{ unique_id }}<br>
    Status: {{ status }}<br>
    Middle Name: {{ middle_name }}<br>
    Username: {{ username }}<br>
    Qualification: {{ qualification }}<br>
    Username: {{ username }}<br>
    Discipline: {{ discipline }}<br>
    Published Work: {{ published_work }}<br>
    Gender: {{ gender }}<br>
    Date of Birth: {{ dob }}<br>
    Age: {{ age }}<br>
    Religion: {{ religion }}<br>
    Phone Number: {{ phone_num }}<br>
    Email: {{ email }}<br>
    height: {{ height }}<br>
    About You: {{ about_me }}

    <h2>Click <a href="{% url 'users:update_examiner' %}">HERE</a> to update your profile</h2>
    <h2>Click <a href="{% url 'exam_question:exam_register' %}">HERE</a> to register for exams</h2>
    <h2>Click <a href="{% url 'exam_question:choose_exam' %}">HERE</a> to set exam questions</h2>

{% endblock content %}
choose_exam

users/templates/users/examiner_profile.html
{% extends 'landing/base1.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Examiner Profile{% endblock %}

{% block content %}
    <div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <strong>Username: {{ user }}</strong><br>
        <strong>Status: {{ status }}</strong><br><br>
        {{ examiner_form|crispy }}
        <p><input type="submit" value="Update"></p>
    </form>
{% endblock %}

users/templates/users/examiner_profile_detail.html
{% extends 'landing/base1.html' %}
{% load static %}

{% block title %}Exaniners Profile Details{% endblock %}

{% block content %}
    <div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <div>
        <h2>Welcome, {{ title }}. {{ first_name }} {{ last_name }},</h2>
        <h2>Here are your personal profile details:</h2>
        <div>
            <p>
                <strong>
                    User id: {{ unique_id }}<br>
                    Middle Name: {{ middle_name }}<br>
                    Status: {{ status }}<br>
                    Qualification: {{ qualification }}<br>
                    Discipline: {{ discipline }}<br>
                    Published Work: <a href="{{ published_work }}">{{ published_work }}</a><br>
                    Gender: {{ gender }}<br>
                    Age: {{ age }}<br>
                    Address: {{ address }}<br>
                    Religion: {{ religion }}<br>
                    Phone Number: {{ phone_num }}<br>
                    Email: {{ email }}<br>
                    Height: {{ height }}<br>
                    About You: {{ about_me }}<br>
                </strong>
            </p>
        </div>

        <div>
            <h2>Click <a href="{% url 'users:update_examiner' %}">HERE</a> to update your profile</h2>
            <h2>Click <a href="{% url 'exam_question:exam_register' %}">HERE</a> to register for exams</h2>
            <h2>Click <a href="{% url 'exam_question:choose_exam' %}">HERE</a> to set exam questions</h2>
        </div>
    </div>
{% endblock content %}

users/templates/users/signup_success.html
{% extends 'landing/base1.html' %}
{% load static %}

{% block title %}Sign Up Success{% endblock %}

{% block content %}
    <p>
        Sign Up Successful!!!<br>
        Proceed to <a href="{% url 'users:login' %}">Log In</a>
    </p>
{% endblock content %}