exam_question/urls.py
from django.urls import path

from exam_question import views, list_views

app_name = 'exam_question'

urlpatterns = [
    path('exam_register/', list_views.examiner_exam_reg, name='exam_register'),
    path('choose_exam/', views.choose_exam, name='choose_exam'),
    path('check_question/', views.check_question, name='check_question'),
    path('my_details/', list_views.examiner_details, name='my_details'),
    path('my_questions/', list_views.list_questions, name='my_questions'),
    path('edit/<str:question_id>/', views.edit_question, name='edit'),


    # financial accounting questions
    path('account_ss1/', views.accounts_ss1, name='account_1'),
    path('account_ss2/', views.accounts_ss2, name='account_2'),
    path('account_ss3/', views.accounts_ss3, name='account_3'),

    # agric questions
    path('agric_ss1/', views.agric_ss1, name='agric_1'),
    path('agric_ss2/', views.agric_ss2, name='agric_2'),
    path('agric_ss3/', views.agric_ss3, name='agric_3'),

    # biology questions
    path('biology_ss1/', views.biology_ss1, name='biology_1'),
    path('biology_ss2/', views.biology_ss2, name='biology_2'),
    path('biology_ss3/', views.biology_ss3, name='biology_3'),

    # chemistry questions
    path('chemistry_ss1/', views.chemistry_ss1, name='chemistry_1'),
    path('chemistry_ss2/', views.chemistry_ss2, name='chemistry_2'),
    path('chemistry_ss3/', views.chemistry_ss3, name='chemistry_3'),

    # civic questions
    path('civic_ss1/', views.civic_ss1, name='civic_1'),
    path('civic_ss2/', views.civic_ss2, name='civic_2'),
    path('civic_ss3/', views.civic_ss3, name='civic_3'),

    # commerce questions
    path('commerce_ss1/', views.commerce_ss1, name='commerce_1'),
    path('commerce_ss2/', views.commerce_ss2, name='commerce_2'),
    path('commerce_ss3/', views.commerce_ss3, name='commerce_3'),

    # crs questions
    path('crs_ss1/', views.crs_ss1, name='crs_1'),
    path('crs_ss2/', views.crs_ss2, name='crs_2'),
    path('crs_ss3/', views.crs_ss3, name='crs_3'),

    # economics questions
    path('economics_ss1/', views.economics_ss1, name='economics_1'),
    path('economics_ss2/', views.economics_ss2, name='economics_2'),
    path('economics_ss3/', views.economics_ss3, name='economics_3'),

    # english literature questions
    path('eng_literature_ss1/', views.eng_literature_ss1, name='eng_lit_1'),
    path('eng_literature_ss2/', views.eng_literature_ss2, name='eng_lit_2'),
    path('eng_literature_ss3/', views.eng_literature_ss3, name='eng_lit_3'),

    # english questions
    path('english_ss1/', views.english_ss1, name='english_1'),
    path('english_ss2/', views.english_ss2, name='english_2'),
    path('english_ss3/', views.english_ss3, name='english_3'),

    # further mathematics questions
    path('further_maths_ss1/', views.further_maths_ss1, name='further_maths_1'),
    path('further_maths_ss2/', views.further_maths_ss2, name='further_maths_2'),
    path('further_maths_ss3/', views.further_maths_ss3, name='further_maths_3'),

    # geography questions
    path('geography_ss1/', views.geography_ss1, name='geography_1'),
    path('geography_ss2/', views.geography_ss2, name='geography_2'),
    path('geography_ss3/', views.geography_ss3, name='geography_3'),

    # government questions
    path('government_ss1/', views.government_ss1, name='government_1'),
    path('government_ss2/', views.government_ss2, name='government_2'),
    path('government_ss3/', views.government_ss3, name='government_3'),

    # marketing questions
    path('marketing_ss1/', views.marketing_ss1, name='marketing_1'),
    path('marketing_ss2/', views.marketing_ss2, name='marketing_2'),
    path('marketing_ss3/', views.marketing_ss3, name='marketing_3'),

    # mathematics questions
    path('maths_ss1/', views.maths_ss1, name='maths_1'),
    path('maths_ss2/', views.maths_ss2, name='maths_2'),
    path('maths_ss3/', views.maths_ss3, name='maths_3'),

    # physics questions
    path('physics_ss1/', views.physics_ss1, name='physics_1'),
    path('physics_ss2/', views.physics_ss2, name='physics_2'),
    path('physics_ss3/', views.physics_ss3, name='physics_3'),

    # yoruba questions
    path('yoruba_ss1/', views.yoruba_ss1, name='yoruba_1'),
    path('yoruba_ss2/', views.yoruba_ss2, name='yoruba_2'),
    path('yoruba_ss3/', views.yoruba_ss3, name='yoruba_3'),

]

exams/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from . import views
from django.conf import settings

app_name = 'exams'

urlpatterns = [
    path('add_department/', views.add_department, name='add_department'),
    path('add_department_save/', views.add_department_save, name='add_department_save'),
    path('edit_department/', views.edit_department, name='edit_department'),
    path('edit_department_save/', views.edit_department_save, name='edit_department_save'),
    path('add_subject/', views.add_subject, name='add_subject'),
    path('add_subject_save/', views.add_subject_save, name='add_subject_save'),
    path('add_student_class/', views.add_student_class, name='add_student_class'),
    path('add_student_class_save/', views.add_student_class_save, name='add_student_class_save'),
    path('add_student_level/', views.add_student_level, name='add_student_level'),
    path('add_student_level_save/', views.add_student_level_save, name='add_student_level_save'),

    path('ajax_question/', views.set_ajax_question, name='ajax_question'),
    path('create_question/', views.CreateQuestion.as_view(), name='create_question'),
    path('update_question/', views.UpdateQuestion.as_view(), name='update_question'),

    path('radio_question/', views.answer, name='radio_question'),

    path('register/', views.register_exam, name='register_exam'),
    path('question/', views.exam_question, name='question'),
    path('answer/', views.student_answer, name='answer'),

]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

'''
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''

school_online/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls', namespace='landing')),
    path('users/', include('users.urls', namespace='users')),
    path('exams/', include('exams.urls', namespace='exams')),
    path('question/', include('set_question.urls', namespace='question')),
    path('exam_question/', include('exam_question.urls', namespace='exam_question')),
    path('student/', include('students.urls', namespace='student'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam_question/models.py
from django.db import models

# Create your models here.

exam_question/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.shortcuts import render

from exams.models import Question, Department, StudentClass, StudentLevel, Subjects

def choose_exam(request):
    return render(request, 'exam_question/choose_exam.html')

def check_question(request):
    return render(request, 'exam_question/check_question.html')


def edit_question(request, question_id):
    question = Question.objects.get(id=question_id)
    examiner = get_user_model().objects.get(username=request.user)

    if request.method == 'POST':
        question = request.POST.get('question')
        option_A = request.POST.get('option_A')
        option_B = request.POST.get('option_B')
        option_C = request.POST.get('option_C')
        option_D = request.POST.get('option_D')
        answer = request.POST.get('answer')

        q = Question.objects.get(id=question_id)
        q.question = question
        q.option_A = option_A
        q.option_B = option_B
        q.option_C = option_C
        q.option_D = option_D
        q.answer = answer
        q.save()

        questions = Question.objects.filter(examiner=request.user).order_by('pk')
        context = {
            'questions': questions
        }
        messages.success(request, "Successfully Edited Question")
        return render(request, 'exam_question/edit_question.html')
    else:
        messages.error(request, "Failed to Edit Question")

    return render(request, 'exam_question/edit_question.html', {'question': question, 'examiner': examiner, 'id': question_id })

# financial accounts question

def accounts_ss1(request):
    examiner = get_user_model().objects.get(username=request.user)
    questions = Question.objects.filter(examiner=request.user).order_by('pk')
    departments = Department.objects.filter(department='Commercial Class')
    stds_class = StudentClass.objects.filter(student_class='SSS')
    stds_level = StudentLevel.objects.filter(student_level=1)
    subjects = Subjects.objects.filter(subject_name='Financial Accounting') #add subject_code

    if request.method == 'POST':
        examiner_id = request.POST.get('examiner')
        department_id = request.POST.get('department')
        student_class_id = request.POST.get('student_class')
        student_level_id = request.POST.get('student_level')
        subject_id = request.POST.get('subject')
        question  = request.POST.get('question')
        option_A = request.POST.get('option_A')
        option_B = request.POST.get('option_B')
        option_C = request.POST.get('option_C')
        option_D = request.POST.get('option_D')
        answer = request.POST.get('correct_answer')

        examiner = get_user_model().objects.get(id=examiner_id)
        department = Department.objects.get(id=department_id)
        student_class = StudentClass.objects.get(id=student_class_id)
        student_level = StudentLevel.objects.get(id=student_level_id)
        subject = Subjects.objects.get(id=subject_id)

        question_add = Question(examiner=examiner,
                                department=department,
                                student_class=student_class,
                                student_level=student_level,
                                subject=subject,
                                question=question,
                                option_A=option_A,
                                option_B=option_B,
                                option_C=option_C,
                                option_D=option_D,
                                answer=answer
                                )
        question_add.save()
        questions = Question.objects.filter(examiner=request.user, student_class=student_class, student_level=student_level, subject=subject).order_by('pk')
        context = {
            'questions': questions
        }
        messages.success(request, "Successfully Added Question")
        return render(request, 'exam_question/question/account/account_1_summary.html', context)

    if stds_class and stds_level and subjects and departments:
        return render(request, 'exam_question/question/account/account_ss1.html', {
            'questions': questions,
            'examiner': examiner,
            'departments': departments,
            'stds_class': stds_class,
            'stds_level': stds_level,
            'subjects': subjects
        })
    else:
        messages.error(request, "You Cannot Add This Question!!!")
        return render(request, 'exam_question/choose_exam.html')


def accounts_ss2(request):
    examiner = get_user_model().objects.get(username=request.user)
    questions = Question.objects.filter(examiner=request.user).order_by('pk')
    departments = Department.objects.filter(department='Commercial Class')
    stds_class = StudentClass.objects.filter(student_class='SSS')
    stds_level = StudentLevel.objects.filter(student_level=2)
    subjects = Subjects.objects.filter(subject_name='Financial Accounting')

    if request.method == 'POST':
        examiner_id = request.POST.get('examiner')
        department_id = request.POST.get('department')
        student_class_id = request.POST.get('student_class')
        student_level_id = request.POST.get('student_level')
        subject_id = request.POST.get('subject')
        question  = request.POST.get('question')
        option_A = request.POST.get('option_A')
        option_B = request.POST.get('option_B')
        option_C = request.POST.get('option_C')
        option_D = request.POST.get('option_D')
        answer = request.POST.get('correct_answer')

        examiner = get_user_model().objects.get(id=examiner_id)
        department = Department.objects.get(id=department_id)
        student_class = StudentClass.objects.get(id=student_class_id)
        student_level = StudentLevel.objects.get(id=student_level_id)
        subject = Subjects.objects.get(id=subject_id)

        question_add = Question(examiner=examiner,
                                department=department,
                                student_class=student_class,
                                student_level=student_level,
                                subject=subject,
                                question=question,
                                option_A=option_A,
                                option_B=option_B,
                                option_C=option_C,
                                option_D=option_D,
                                answer=answer
                                )
        question_add.save()
        questions = Question.objects.filter(examiner=request.user, student_class=student_class, student_level=student_level, subject=subject).order_by('pk')
        context = {
            'questions': questions
        }
        messages.success(request, "Successfully Added Question")
        return render(request, 'exam_question/question/account/account_2_summary.html', context)

    if stds_class and stds_level and subjects and departments:
        return render(request, 'exam_question/question/account/account_ss2.html', {
            'questions': questions,
            'examiner': examiner,
            'departments': departments,
            'stds_class': stds_class,
            'stds_level': stds_level,
            'subjects': subjects
        })
    else:
        messages.error(request, "You Cannot Add This Question!!!")
        return render(request, 'exam_question/choose_exam.html')


def accounts_ss3(request):
    examiner = get_user_model().objects.get(username=request.user)
    questions = Question.objects.filter(examiner=request.user).order_by('pk')
    departments = Department.objects.filter(department='Commercial Class')
    stds_class = StudentClass.objects.filter(student_class='SSS')
    stds_level = StudentLevel.objects.filter(student_level=3)
    subjects = Subjects.objects.filter(subject_name='Financial Accounting')

    if request.method == 'POST':
        examiner_id = request.POST.get('examiner')
        department_id = request.POST.get('department')
        student_class_id = request.POST.get('student_class')
        student_level_id = request.POST.get('student_level')
        subject_id = request.POST.get('subject')
        question  = request.POST.get('question')
        option_A = request.POST.get('option_A')
        option_B = request.POST.get('option_B')
        option_C = request.POST.get('option_C')
        option_D = request.POST.get('option_D')
        answer = request.POST.get('correct_answer')

        examiner = get_user_model().objects.get(id=examiner_id)
        department = Department.objects.get(id=department_id)
        student_class = StudentClass.objects.get(id=student_class_id)
        student_level = StudentLevel.objects.get(id=student_level_id)
        subject = Subjects.objects.get(id=subject_id)

        question_add = Question(examiner=examiner,
                                department=department,
                                student_class=student_class,
                                student_level=student_level,
                                subject=subject,
                                question=question,
                                option_A=option_A,
                                option_B=option_B,
                                option_C=option_C,
                                option_D=option_D,
                                answer=answer
                                )
        question_add.save()
        questions = Question.objects.filter(examiner=request.user, student_class=student_class, student_level=student_level, subject=subject).order_by('pk')
        context = {
            'questions': questions
        }
        messages.success(request, "Successfully Added Question")
        return render(request, 'exam_question/question/account/account_3_summary.html', context)

    if stds_class and stds_level and subjects and departments:

exam_question/templates/exam_question/question/marketing/marketing_1_summary.html
{% extends 'landing/base1.html' %}

{% block title %}EXAMINERS' QUESTION SUMMARY{% endblock title %}

{% block style %}

{% endblock style %}

{% block content %}
    <div class="form-group">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                {% endif %}

                {% if message.tags == 'success' %}
                    <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <h1>The Summary of your question is as follows:</h1><br>
    {% for question in questions %}

        <h2>Question {{ question.id }}: {{ question.question }}</h2>
        <h2>A: {{ question.option_A }}</h2>
        <h2>B: {{ question.option_B }}</h2>
        <h2>C: {{ question.option_C }}</h2>
        <h2>D: {{ question.option_D }}</h2>
        <h1>The correct answer is {{ question.answer }} </h1><br>

        <a href="{% url 'exam_question:edit' question.id %}" class="btn btn-success">EDIT</a>
        <a href="#" class="btn btn-danger">DELETE</a>
    {% endfor %}
        <p>Top</p>
        <p>Click <strong><a href="{% url 'exam_question:marketing_1' %}">here</a></strong> to add another question</p>
        <p>Finished setting your questions? Go <a href="#">Home</a></p>

{% endblock content %}

exam_question/templates/exam_question/question/marketing/marketing_2_summary.html
{% extends 'landing/base1.html' %}

{% block title %}EXAMINERS' QUESTION SUMMARY{% endblock title %}

{% block style %}

{% endblock style %}

{% block content %}
    <div class="form-group">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                {% endif %}

                {% if message.tags == 'success' %}
                    <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <h1>The Summary of your question is as follows:</h1><br>
    {% for question in questions %}

        <h2>Question {{ question.id }}: {{ question.question }}</h2>
        <h2>A: {{ question.option_A }}</h2>
        <h2>B: {{ question.option_B }}</h2>
        <h2>C: {{ question.option_C }}</h2>
        <h2>D: {{ question.option_D }}</h2>
        <h1>The correct answer is {{ question.answer }} </h1><br>

        <a href="{% url 'exam_question:edit' question.id %}" class="btn btn-success">EDIT</a>
        <a href="#" class="btn btn-danger">DELETE</a>
    {% endfor %}
        <p>Top</p>
        <p>Click <strong><a href="{% url 'exam_question:marketing_2' %}">here</a></strong> to add another question</p>
        <p>Finished setting your questions? Go <a href="#">Home</a></p>

{% endblock content %}

exam_question/templates/exam_question/question/marketing/marketing_3_summary.html
{% extends 'landing/base1.html' %}

{% block title %}EXAMINERS' QUESTION SUMMARY{% endblock title %}

{% block style %}

{% endblock style %}

{% block content %}
    <div class="form-group">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                {% endif %}

                {% if message.tags == 'success' %}
                    <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <h1>The Summary of your question is as follows:</h1><br>
    {% for question in questions %}

        <h2>Question {{ question.id }}: {{ question.question }}</h2>
        <h2>A: {{ question.option_A }}</h2>
        <h2>B: {{ question.option_B }}</h2>
        <h2>C: {{ question.option_C }}</h2>
        <h2>D: {{ question.option_D }}</h2>
        <h1>The correct answer is {{ question.answer }} </h1><br>

        <a href="{% url 'exam_question:edit' question.id %}" class="btn btn-success">EDIT</a>
        <a href="#" class="btn btn-danger">DELETE</a>
    {% endfor %}
        <p>Top</p>
        <p>Click <strong><a href="{% url 'exam_question:marketing_3' %}">here</a></strong> to add another question</p>
        <p>Finished setting your questions? Go <a href="#">Home</a></p>

{% endblock content %}

exam_question/templates/exam_question/question/marketing/marketing_ss1.html
{% extends 'landing/base1.html' %}
{% load static %}


{% block title %}Exams in Django Ajax{% endblock %}

{% block content %}

    <!-- Add New Exam Form Page -->
    <div class="container">
        <h1>Exam Questions</h1>
        <div class="row">
            <div class="col-md-8 ">
                <h3>Add New Question</h3>
                <form id="addQuestion" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        {% if messages %}
                            {% for message in messages %}
                                {% if message.tags == 'error' %}
                                    <div class="alert alert-danger" style="margin-top:10px">
                                        {{ message }}
                                    </div>
                                {% endif %}
                                {% if message.tags == 'success' %}
                                    <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label>Examiner:</label>
                        <select class="form-control" name="examiner" id='examiner'>
                            <option value="{{ examiner.id }}">{{ examiner.first_name }} {{ examiner.last_name }}</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label>Department:</label>
                        <select class="form-control" name="department" id='department'>
                            {% for dept in departments %}
                                <option value="{{ dept.id }}">{{ dept.department }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label>Student Class:</label>
                        <select class="form-control" name="student_class" id='student_class'>
                            {% for std_class in stds_class %}
                                <option value="{{ std_class.id }}">{{ std_class.student_class }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label>Student Level:</label>
                        <select class="form-control" name="student_level" id='student_level'>
                            {% for std_level in stds_level %}
                                <option value="{{ std_level.id }}">{{ std_level.student_level }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label>Subject:</label>
                        <select class="form-control" name="subject" id='subject'>
                            {% for subject in subjects %}
                                <option value="{{ subject.id }}">{{ subject.subject_name }} ({{ subject.subject_code }})</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label>Question:</label>
                        <input class="form-control" type="text" name="question"  style="width: 200px; height: 100px;" placeholder="Enter Your Question" required>
                    </div>

                    <div class="form-group">
                        <label>Option A:</label>
                        <input class="form-control" type="text" name="option_A" placeholder="Enter option A" required>
                    </div>

                    <div class="form-group">
                        <label>Option B:</label>
                        <input class="form-control" type="text" name="option_B" placeholder="Enter option B" required>
                    </div>

                    <div class="form-group">
                        <label>Option C:</label>
                        <input class="form-control" type="text" name="option_C" placeholder="Enter option C" required>
                    </div>

                    <div class="form-group">
                        <label>Option D:</label>
                        <input class="form-control" type="text" name="option_D" placeholder="Enter option D" required>
                    </div>

                    <div class="form-group">
                        <label>Correct Answer:</label>
                        <input class="form-control" type="text" name="correct_answer" placeholder="Enter Correct Answer" maxlength="1" required>
                    </div>

                    <button id='button' class="btn btn-primary form-control" type="submit">SUBMIT QUESTION</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}